import logging

import pytest
from ophyd.sim import make_fake_device

from pcdsdevices.sample_delivery import SDS

logger = logging.getLogger(__name__)


@pytest.mark.timeout(5)
def test_sds_init():
    logger.debug('test_sds_init')
    FakeJet = make_fake_device(SDS)
    FakeJet('TST', name='test',
            flow_integrator_integrator_source_prefix='test1',
            flow_integrator_flow_source_prefix='test2',
            flow_integrator_names_prefix='test3',
            flow_integrator_start1_prefix='test4',
            flow_integrator_used1_prefix='test5',
            flow_integrator_time1_prefix='test6',
            flow_integrator_start2_prefix='test7',
            flow_integrator_used2_prefix='test8',
            flow_integrator_time2_prefix='test9',
            flow_integrator_start3_prefix='test10',
            flow_integrator_used3_prefix='test11',
            flow_integrator_time3_prefix='test12',
            flow_integrator_start4_prefix='test13',
            flow_integrator_used4_prefix='test14',
            flow_integrator_time4_prefix='test15',
            flow_integrator_start5_prefix='test16',
            flow_integrator_used5_prefix='test17',
            flow_integrator_time5_prefix='test18',
            flow_integrator_start6_prefix='test19',
            flow_integrator_used6_prefix='test20',
            flow_integrator_time6_prefix='test21',
            flow_integrator_start7_prefix='test22',
            flow_integrator_used7_prefix='test23',
            flow_integrator_time7_prefix='test24',
            flow_integrator_start8_prefix='test25',
            flow_integrator_used8_prefix='test26',
            flow_integrator_time8_prefix='test27',
            flow_integrator_start9_prefix='test28',
            flow_integrator_used9_prefix='test29',
            flow_integrator_time9_prefix='test30',
            flow_integrator_start10_prefix='test31',
            flow_integrator_used10_prefix='test32',
            flow_integrator_time10_prefix='test33',
            pressure_controller_status_prefix='test34',
            pressure_controller_pressure1_prefix='test35',
            pressure_controller_enabled1_prefix='test36',
            pressure_controller_limit1_prefix='test37',
            pressure_controller_SP1_prefix='test38',
            pressure_controller_pressure2_prefix='test39',
            pressure_controller_enabled2_prefix='test40',
            pressure_controller_limit2_prefix='test41',
            pressure_controller_SP2_prefix='test42',
            hplc_status_prefix='test43',
            hplc_run_prefix='test44',
            hplc_flowrate_prefix='test45',
            hplc_set_flowrate_prefix='test46',
            hplc_flowrate_SP_prefix='test47',
            hplc_pressure_prefix='test48',
            hplc_pressure_units_prefix='test49',
            hplc_set_max_pressure_prefix='test50',
            hplc_max_pressure_prefix='test51',
            hplc_clear_error_prefix='test52',
            cooler_shaker_temperature1_prefix='test53',
            cooler_shaker_SP1_prefix='test54',
            cooler_shaker_set_SP1_prefix='test55',
            cooler_shaker_current1_prefix='test56',
            cooler_shaker_temperature2_prefix='test57',
            cooler_shaker_SP2_prefix='test58',
            cooler_shaker_set_SP2_prefix='test59',
            cooler_shaker_current2_prefix='test60',
            cooler_shaker_reboot_prefix='test61',
            selector_remote_control_prefix='test62',
            selector_status_prefix='test63', selector_flow_prefix='test64',
            selector_flowstate_prefix='test65',
            selector_flowtype_prefix='test66',
            selector_FM_rb_prefix='test67', selector_FM_reset_prefix='test68',
            selector_FM_prefix='test69', selector_names_button_prefix='test70',
            selector_couple_button_prefix='test71',
            selector_names1_prefix='test72',
            selector_names2_prefix='test73', selector_shaker1_prefix='test74',
            selector_shaker2_prefix='test75', selector_shaker3_prefix='test76',
            selector_shaker4_prefix='test77', selector_prefix='test78',
            cooler_shaker_prefix='test79', hplc_prefix='test80',
            pressure_controller_prefix='test81',
            flow_integrator_prefix='test82')


@pytest.mark.timeout(5)
def test_sds_disconnected():
    logger.debug('test_sds_disconnected')
    SDS('TST', name='test', flow_integrator_integrator_source_prefix='test1',
        flow_integrator_flow_source_prefix='test2',
        flow_integrator_names_prefix='test3',
        flow_integrator_start1_prefix='test4',
        flow_integrator_used1_prefix='test5',
        flow_integrator_time1_prefix='test6',
        flow_integrator_start2_prefix='test7',
        flow_integrator_used2_prefix='test8',
        flow_integrator_time2_prefix='test9',
        flow_integrator_start3_prefix='test10',
        flow_integrator_used3_prefix='test11',
        flow_integrator_time3_prefix='test12',
        flow_integrator_start4_prefix='test13',
        flow_integrator_used4_prefix='test14',
        flow_integrator_time4_prefix='test15',
        flow_integrator_start5_prefix='test16',
        flow_integrator_used5_prefix='test17',
        flow_integrator_time5_prefix='test18',
        flow_integrator_start6_prefix='test19',
        flow_integrator_used6_prefix='test20',
        flow_integrator_time6_prefix='test21',
        flow_integrator_start7_prefix='test22',
        flow_integrator_used7_prefix='test23',
        flow_integrator_time7_prefix='test24',
        flow_integrator_start8_prefix='test25',
        flow_integrator_used8_prefix='test26',
        flow_integrator_time8_prefix='test27',
        flow_integrator_start9_prefix='test28',
        flow_integrator_used9_prefix='test29',
        flow_integrator_time9_prefix='test30',
        flow_integrator_start10_prefix='test31',
        flow_integrator_used10_prefix='test32',
        flow_integrator_time10_prefix='test33',
        pressure_controller_status_prefix='test34',
        pressure_controller_pressure1_prefix='test35',
        pressure_controller_enabled1_prefix='test36',
        pressure_controller_limit1_prefix='test37',
        pressure_controller_SP1_prefix='test38',
        pressure_controller_pressure2_prefix='test39',
        pressure_controller_enabled2_prefix='test40',
        pressure_controller_limit2_prefix='test41',
        pressure_controller_SP2_prefix='test42',
        hplc_status_prefix='test43',
        hplc_run_prefix='test44',
        hplc_flowrate_prefix='test45',
        hplc_set_flowrate_prefix='test46',
        hplc_flowrate_SP_prefix='test47',
        hplc_pressure_prefix='test48',
        hplc_pressure_units_prefix='test49',
        hplc_set_max_pressure_prefix='test50',
        hplc_max_pressure_prefix='test51',
        hplc_clear_error_prefix='test52',
        cooler_shaker_temperature1_prefix='test53',
        cooler_shaker_SP1_prefix='test54',
        cooler_shaker_set_SP1_prefix='test55',
        cooler_shaker_current1_prefix='test56',
        cooler_shaker_temperature2_prefix='test57',
        cooler_shaker_SP2_prefix='test58',
        cooler_shaker_set_SP2_prefix='test59',
        cooler_shaker_current2_prefix='test60',
        cooler_shaker_reboot_prefix='test61',
        selector_remote_control_prefix='test62',
        selector_status_prefix='test63', selector_flow_prefix='test64',
        selector_flowstate_prefix='test65',
        selector_flowtype_prefix='test66',
        selector_FM_rb_prefix='test67', selector_FM_reset_prefix='test68',
        selector_FM_prefix='test69', selector_names_button_prefix='test70',
        selector_couple_button_prefix='test71',
        selector_names1_prefix='test72',
        selector_names2_prefix='test73', selector_shaker1_prefix='test74',
        selector_shaker2_prefix='test75', selector_shaker3_prefix='test76',
        selector_shaker4_prefix='test77', selector_prefix='test78',
        cooler_shaker_prefix='test79', hplc_prefix='test80',
        pressure_controller_prefix='test81',
        flow_integrator_prefix='test82')
