{% set package_name = "pcdsdevices" %}
{% set import_name = "pcdsdevices" %}
{% set version = load_file_regex(load_file=os.path.join(import_name, "_version.py"), regex_pattern=".*version = '(\S+)'").group(1) %}

package:
  name: {{ package_name }}
  version : {{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.9
    - pip
    - setuptools_scm
  run:
    - python >=3.9
    - bluesky-base >=1.6.4
    - happi
    - jsonschema
    - lightpath-base >=1.0.5
    - matplotlib-base
    - numpy
    - ophyd >=1.7.0
    - pcdscalc >=0.2.0
    - pcdsutils >=0.4.0
    - prettytable
    - pyepics >=3.4.2,<3.5.8
    - pytmc >=2.7.0
    - pyyaml
    - schema
    - scipy
    - sympy
  run_constrained:
    - pmgr >=2.0.2
    - typhos >=2.4.0

test:
  requires:
    - pytest
    - pytest-timeout
    - typhos
  imports:
    - {{ import_name }}

about:
  home: https://github.com/pcdshub/pcdsdevices
  license: SLAC Open License
  summary: IOC definitions for LCLS Beamline Devices
